### ISSUE TITLE
Nuxt 3?

### ISSUE THREAD

**Issue by Hibrix-net** [MaxMonteil/MyloWebsite#18]
Hello,

Thanks for this great contribution. I'm just wondering if there are plans to upgrade the project to Nuxt 3, since they will release the stable  version in 2 weeks.

Kind regards,

**Comment by MaxMonteil** [comment]
Hey, I only just now saw this comment!

I've just finished rewriting the site with Nuxt 3 :D

**Comment by Hibrix-net** [comment]
> Hey, I only just now saw this comment!
> 
> I've just finished rewriting the site with Nuxt 3 :D

Hello,

Many thanks. Any plans to also update the repository?

Best regards,

**Comment by MaxMonteil** [comment]
Definitely, right now you can check out the branch as is. I'll be merging this into main Monday evening when I'm ready to release the full thing.

**Comment by Hibrix-net** [comment]
> Definitely, right now you can check out the branch as is. I'll be merging this into main Monday evening when I'm ready to release the full thing.
> 
> Still adding a couple of things

Many thanks again.

Best regards,
